version: '3'
services: 
  mongodb-container:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - my-network
  user-microservice:
    build:
      context: ./user-service
      dockerfile: Dockerfile 
    ports:
      - "9998:9998"
    links:
      - mongodb-container
    networks:
      - my-network

  order-microservice:
    build:
      context: ./order-service
      dockerfile: Dockerfile 
    ports:
      - "9997:9997"
    links:
      - mongodb-container
    networks:
      - my-network

  product-microservice:
    build:
      context: ./product-service
      dockerfile: Dockerfile 
    ports:
      - "9996:9996"
    links:
      - mongodb-container
    networks:
      - my-network
networks:
  my-network:
    driver: bridge